# Generated by Django 2.1.5 on 2019-02-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofprod', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=20)),
            ],
        ),
    ]
