# Generated by Django 2.1.5 on 2019-02-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_orderinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='price',
            new_name='totalprice',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='nameofprod',
        ),
    ]
