# Generated by Django 2.1.5 on 2019-02-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_contactinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_seller',
        ),
    ]
