# Generated by Django 2.1.5 on 2019-03-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20190228_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='products',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
