# Generated by Django 2.1.5 on 2019-03-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_orderinfo_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='products',
            field=models.CharField(default='Unavailable', max_length=200),
        ),
    ]
