# Generated by Django 2.1.5 on 2019-03-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20190301_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='products',
            field=models.CharField(max_length=200),
        ),
    ]
