# Generated by Django 2.1.5 on 2019-02-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_customseller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customseller',
            old_name='company_addredd',
            new_name='company_address',
        ),
    ]
