# Generated by Django 2.1.5 on 2019-03-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20190301_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartinfo',
            name='seller',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.CustomSeller'),
            preserve_default=False,
        ),
    ]
