# Generated by Django 2.1.5 on 2019-03-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_cartinfo_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=75)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.CustomSeller')),
            ],
        ),
    ]
