# Generated by Django 2.1.5 on 2019-03-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_sellerorderinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerorderinfo',
            name='customer',
        ),
    ]
