# Generated by Django 2.1.5 on 2019-02-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_productsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinfo',
            name='colors',
            field=models.CharField(default='All', max_length=18),
        ),
    ]
