# Generated by Django 2.1.5 on 2019-02-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_productsinfo_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinfo',
            name='categories',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
