# Generated by Django 2.1.5 on 2019-03-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_remove_sellerorderinfo_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerorderinfo',
            name='customer',
            field=models.CharField(default='Anonymous', max_length=75),
        ),
    ]
