# Generated by Django 2.1.5 on 2019-02-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_productsinfo_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsinfo',
            old_name='categories',
            new_name='category',
        ),
    ]
