# Generated by Django 2.1.5 on 2019-02-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20190225_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinfo',
            name='price',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
