# Generated by Django 2.1.5 on 2019-03-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_auto_20190315_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='orderstatus',
            field=models.CharField(choices=[('NOTCNF', 'Not Confirmed'), ('CNFORM', 'Order Confirmed'), ('DSPATC', 'Order Dispatched'), ('DLIVER', 'Order Delivered')], default='NOTCNF', max_length=6),
        ),
    ]
