# Generated by Django 2.1.5 on 2019-03-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_orderinfo_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='orderInvoiceNum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='paymentstatus',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('PENDING', 'Pending'), ('DECLINED', 'Declined')], default='PENDING', max_length=9),
        ),
    ]
